version: '3.5'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src