version: '3.5'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'